import type { NextPage } from 'next';
import Head from 'next/head';
import GamesPage from '../features/games/GamesPage';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <GamesPage />
      </main>
    </div>
  );
};

export default Home;
